language: nix
matrix:
  include:
    - env: CHANNEL=https://nixos.org/channels/nixos-18.09
    - env: CHANNEL=https://nixos.org/channels/nixpkgs-unstable
script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - ./hack/ci.sh
